### PR TITLE
Handle repetition separator

### PR DESCRIPTION
**Pull request by samuel-chane**

### CODE REVIEW

**Comment by senaranya** [comment]
Can you please create an issue for this PR describing the problem, possibly with an example?

**Comment by senaranya** [comment]
Disregard my previous comment. There was another issue and a related PR open with the same - 
Issue: https://github.com/senaranya/HL7/issues/20
PR: https://github.com/senaranya/HL7/pull/21

Are these the same problem and fix as yours?

**Comment by samuel-chane** [comment]
yes it looks like same, but it looks abandoned.
So i created a new PR

**Comment by senaranya** [comment]
Ok, in that case it'll be great if you open a new issue with problem description and example

**Pull request merged**
